# Define the landing page
"/": blog

# Shared behaviour
"(:alpha).xml": controller=$1&action=xml&ajax=1
"(:alpha)/page/(:num)": controller=$1&page=$2
"(:alpha)/(create|update|destroy)": controller=$1&action=$2
"(:alpha)/(:num)/(create|update|destroy)": controller=$1&id=$2&action=$3
"(:alpha)/(:num)/highlight/(:any)": controller=$1&id=$2&highlight=$3
"(:alpha)/(:num)/page/(:num)": controller=$1&id=$2&page=$3

# Special behaviour
"blog/(:num)": controller=blog&id=$1&page=1
"blog/(:num)/(:any)": controller=blog&id=$1&page=1
"calendar/(:num)/archive": controller=calendar&action=archive&id=$1
"comment/(:num)/destroy/(:num)": controller=comment&action=destroy&id=$1&parent_id=$2
"gallery": controller=gallery&page=1
"gallery/(:num)/(createfile|updatefile|destroyfile)": controller=gallery&action=$2&id=$1
"gallery/(:num)/image/(:num)": controller=gallery&action=image&album_id=$1&id=$2
"language/(:alpha)": language=$1
"mail/(:num)/ajax": controller=mail&id=$1&ajax=1
"media/(:any)/destroy": controller=media&action=destroy&file=$1
"rss/(:alpha)": controller=rss&section=$1
"rss/(:alpha)/(:num)": controller=rss&section=$1&id=$2
"search/(:any)": controller=search&search=$1
"session/(password|verification)": controller=session&action=$1
"user/(:num)/(:alpha)": controller=user&action=$2&id=$1
"user/(:alnum)/verification": controller=user&action=verification&code=$1

# Magic rule
"(:alpha)/(:num)": controller=$1&id=$2
"(:alpha)/(:num)/(:any)": controller=$1&id=$2&seo_title=$3

# Fixes
"blog/(:any)": controller=blog&search=$1