"/": blog

"(:alpha).xml": controller=$1&action=xml&ajax=1
"(:alpha)/page/(:num)": controller=$1&page=$2
"(:alpha)/(create|update|destroy)": controller=$1&action=$2
"(:alpha)/(:num)/(create|update|destroy)": controller=$1&id=$2&action=$3
"(:alpha)/(:num)/highlight/(:any)": controller=$1&id=$2&highlight=$3

"blog/(:num)": controller=$1&id=$2
"blog/(:num)/(:any)": controller=blog&id=$1&seo_title=$2
"blog/(:any)": controller=blog&search=$1

"calendar/archive/(:num)": controller=calendar&action=archive&id=$1
"calendar/(:num)": controller=calendar&id=$1&ajax=1

"language/(:alpha)": language=$1